app = "app-control-bot"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  BACKEND_URL = "https://yutube-com-pcu9.onrender.com"
  TELEGRAM_BOT_TOKEN = "8995589618:AAHWxs2-bmpuwZi3BI7LIjppxpdH5-WmYkw"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[services.ports]]
    port = 8080
    handlers = ["tls"]
